# Generated by Django 6.0.6 on 2026-06-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(choices=[('good', 'Bon état'), ('warning', 'Attention nécessaire'), ('critical', 'État critique')], default='good', max_length=10, verbose_name='Statut global')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du diagnostic')),
                ('mileage', models.IntegerField(verbose_name='Kilométrage actuel')),
                ('oil_change_status', models.CharField(blank=True, max_length=50, verbose_name='État vidange')),
                ('inspection_status', models.CharField(blank=True, max_length=50, verbose_name='État contrôle technique')),
                ('insurance_status', models.CharField(blank=True, max_length=50, verbose_name='État assurance')),
                ('registration_status', models.CharField(blank=True, max_length=50, verbose_name='État carte grise')),
                ('days_until_next_oil_change', models.IntegerField(blank=True, null=True, verbose_name='Jours avant prochaine vidange')),
                ('km_until_next_oil_change', models.IntegerField(blank=True, null=True, verbose_name='KM avant prochaine vidange')),
                ('days_until_inspection', models.IntegerField(blank=True, null=True, verbose_name='Jours avant contrôle technique')),
                ('days_until_insurance_expiry', models.IntegerField(blank=True, null=True, verbose_name='Jours avant expiration assurance')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recommandations')),
                ('is_critical', models.BooleanField(default=False, verbose_name='État critique')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_reports', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Rapport de diagnostic',
                'verbose_name_plural': 'Rapports de diagnostic',
                'ordering': ['-report_date'],
            },
        ),
    ]
