# Generated by Django 6.0.6 on 2026-06-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Vidange'), ('brake', 'Freins'), ('tire', 'Pneus'), ('belt', 'Courroie de distribution'), ('battery', 'Batterie'), ('filter', 'Filtres'), ('clutch', 'Embrayage'), ('suspension', 'Suspension'), ('exhaust', 'Échappement'), ('electric', 'Système électrique'), ('air_conditioning', 'Climatisation'), ('timing_belt', 'Distribution'), ('cooling', 'Refroidissement'), ('other', 'Autre')], max_length=30, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('mileage_at_service', models.IntegerField(verbose_name="Kilométrage lors de l'intervention")),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (€)')),
                ('garage_name', models.CharField(blank=True, max_length=200, verbose_name='Garage')),
                ('next_due_mileage', models.IntegerField(blank=True, null=True, verbose_name='Prochain kilométrage recommandé')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Prochaine date recommandée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['-date'],
            },
        ),
    ]
