# Generated by Django 6.0.6 on 2026-08-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('parts', '0001_initial'),
        ('vehicles', '0002_vehicletype_brand_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('interval_km', models.IntegerField(blank=True, null=True, verbose_name='Intervalle (km)')),
                ('interval_months', models.IntegerField(blank=True, null=True, verbose_name='Intervalle (mois)')),
                ('last_service_km', models.IntegerField(blank=True, null=True, verbose_name='Dernier service (km)')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Dernier service (date)')),
                ('status', models.CharField(choices=[('up_to_date', 'À jour'), ('warning', 'À surveiller'), ('critical', 'Critique')], default='up_to_date', max_length=20, verbose_name='Statut')),
                ('recalced_at', models.DateTimeField(blank=True, null=True, verbose_name='Recalculé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracked_items', to='parts.part', verbose_name='Pièce liée')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_items', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Élément suivi',
                'verbose_name_plural': 'Éléments suivis',
                'ordering': ['vehicle', 'name'],
            },
        ),
    ]
