# Generated by Django 6.0.6 on 2026-06-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteGrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, verbose_name="Numéro d'immatriculation")),
                ('issue_date', models.DateField(verbose_name='Date de délivrance')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('document', models.FileField(blank=True, upload_to='documents/cartes_grises/', verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_grise', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Carte Grise',
                'verbose_name_plural': 'Cartes Grises',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Compagnie d'assurance")),
                ('policy_number', models.CharField(max_length=100, verbose_name='Numéro de police')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name="Date d'expiration")),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prime (€/an)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('document', models.FileField(blank=True, upload_to='documents/insurances/', verbose_name='Document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Date du contrôle')),
                ('result', models.CharField(choices=[('passed', 'Favorable'), ('failed', 'Défavorable'), ('partial', 'Favorable avec réserves')], max_length=10, verbose_name='Résultat')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('mileage_at_inspection', models.IntegerField(blank=True, null=True, verbose_name='Kilométrage lors du contrôle')),
                ('garage_name', models.CharField(blank=True, max_length=200, verbose_name='Centre de contrôle')),
                ('document', models.FileField(blank=True, upload_to='documents/inspections/', verbose_name='Document')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_inspections', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Contrôle Technique',
                'verbose_name_plural': 'Contrôles Techniques',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
