# Generated by Django 6.0.6 on 2026-08-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('van', 'Utilitaire'), ('bus', 'Bus'), ('other', 'Autre')], default='car', max_length=20, verbose_name='Type')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year_start', models.IntegerField(blank=True, null=True, verbose_name='Année début')),
                ('year_end', models.IntegerField(blank=True, null=True, verbose_name='Année fin')),
                ('engine_info', models.CharField(blank=True, max_length=200, verbose_name='Motorisation')),
                ('body_type', models.CharField(blank=True, max_length=100, verbose_name='Carrosserie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiche véhicule (encyclopédie)',
                'verbose_name_plural': 'Fiches véhicules (encyclopédie)',
                'ordering': ['brand', 'model', 'year_start'],
                'unique_together': {('vehicle_type', 'brand', 'model', 'year_start', 'year_end')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('oil_change', 'Vidange'), ('brake', 'Freins'), ('tire', 'Pneus'), ('belt', 'Courroie'), ('timing_belt', 'Distribution'), ('battery', 'Batterie'), ('filter', 'Filtres'), ('clutch', 'Embrayage'), ('suspension', 'Suspension'), ('exhaust', 'Échappement'), ('electric', 'Système électrique'), ('air_conditioning', 'Climatisation'), ('cooling', 'Refroidissement'), ('other', 'Autre')], max_length=30, verbose_name='Intervention')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('interval_km', models.IntegerField(blank=True, null=True, verbose_name='Intervalle (km)')),
                ('interval_months', models.IntegerField(blank=True, null=True, verbose_name='Intervalle (mois)')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé (€)')),
                ('vehicle_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='reference.vehiclereference', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': "Plan d'entretien",
                'verbose_name_plural': "Plans d'entretien",
                'ordering': ['intervention_type'],
            },
        ),
    ]
