# Generated by Django 6.0.6 on 2026-08-20 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        ('vehicles', '0002_vehicletype_brand_vehiclemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garage', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Garage',
                'verbose_name_plural': 'Garages',
            },
        ),
        migrations.CreateModel(
            name='GarageStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mechanic', 'Mécanicien'), ('manager', 'Manager'), ('admin', 'Administrateur')], default='mechanic', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='garage.garage', verbose_name='Garage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Employé du garage',
                'verbose_name_plural': 'Employés du garage',
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('quote', 'Devis'), ('in_progress', 'En cours'), ('waiting_parts', 'Attente pièces'), ('invoiced', 'Facturé'), ('cancelled', 'Annulé')], default='quote', max_length=20, verbose_name='Statut')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé (€)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût total (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_repair_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_orders', to='garage.garage', verbose_name='Garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_orders', to='vehicles.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Ordre de réparation',
                'verbose_name_plural': 'Ordres de réparation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire (€)')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_order_parts', to='parts.part')),
                ('repair_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='garage.repairorder')),
            ],
            options={
                'verbose_name': "Pièce d'ordre de réparation",
                'verbose_name_plural': "Pièces d'ordre de réparation",
            },
        ),
    ]
