# Generated by Django 6.0.6 on 2026-06-04 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du véhicule')),
                ('brand', models.CharField(max_length=100, verbose_name='Marque')),
                ('model', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('vehicle_type', models.CharField(choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('van', 'Utilitaire'), ('bus', 'Bus'), ('other', 'Autre')], default='car', max_length=20, verbose_name='Type')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('electric', 'Électrique'), ('hybrid', 'Hybride'), ('lpg', 'GPL'), ('other', 'Autre')], default='gasoline', max_length=20, verbose_name='Carburant')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='Numéro VIN')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name="Numéro d'immatriculation")),
                ('mileage', models.IntegerField(default=0, verbose_name='Kilométrage')),
                ('photo', models.ImageField(blank=True, upload_to='vehicles/', verbose_name='Photo')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['-created_at'],
            },
        ),
    ]
