# Generated by Django 6.0.6 on 2026-08-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Type')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Libellé')),
            ],
            options={
                'verbose_name': 'Type de véhicule (NHTSA)',
                'verbose_name_plural': 'Types de véhicules (NHTSA)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marque')),
                ('nhtsa_id', models.IntegerField(blank=True, null=True, verbose_name='ID NHTSA')),
                ('vehicle_types', models.ManyToManyField(blank=True, related_name='brands', to='vehicles.vehicletype')),
            ],
            options={
                'verbose_name': 'Marque (NHTSA)',
                'verbose_name_plural': 'Marques (NHTSA)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.brand')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='vehicles.vehicletype')),
            ],
            options={
                'verbose_name': 'Modèle (NHTSA)',
                'verbose_name_plural': 'Modèles (NHTSA)',
                'ordering': ['name'],
                'unique_together': {('name', 'brand', 'year', 'vehicle_type')},
            },
        ),
    ]
