# Generated by Django 6.0.6 on 2026-08-20 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicletype_brand_vehiclemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de pièce',
                'verbose_name_plural': 'Catégories de pièces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Voiture'), ('motorcycle', 'Moto'), ('truck', 'Camion'), ('van', 'Utilitaire'), ('bus', 'Bus'), ('other', 'Autre'), ('', 'Tous types')], default='', max_length=20, verbose_name='Type de véhicule')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.partcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='parts.part')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_parts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Compatibilité pièce',
                'verbose_name_plural': 'Compatibilités pièces',
                'unique_together': {('part', 'vehicle')},
            },
        ),
        migrations.AddField(
            model_name='part',
            name='compatible_vehicles',
            field=models.ManyToManyField(blank=True, related_name='parts', through='parts.PartCompatibility', to='vehicles.vehicle', verbose_name='Véhicules compatibles'),
        ),
    ]
